stages:
  - version
  - build
  - test
  - release
  
cache:
  key: "$CI_JOB_NAME"

variables:
  DOCKER_TLS_CERTDIR: ""

version:
  stage: version
  image: registry.gitlab.com/juhani/go-semrel-gitlab:v0.21.1
  script:
    #- printenv
    - release test-git || true
    - release test-api
    - release next-version --allow-current
    - release next-version --allow-current > .next-version
    - echo "RELEASE_URL=$CI_PROJECT_URL/-/tags/v$(<.next-version)" > build_info
    - echo "RELEASE_DESC=\"$(uname -mo) binary\"" >> build_info
    - echo "RELEASE_SHA=$CI_COMMIT_SHORT_SHA" >> build_info
    - echo "RELEASE_VERSION=$(<.next-version)" >> build_info
  artifacts:
    paths:
    - .next-version
    - build_info
  except:
    - tags

# build:
#   stage: build
#   image: docker:19.03.6
#   variables:
#     DOCKER_BUILDKIT: 1
#     # For Container Scanning
#     IMAGE_TAG: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA
#   services:
#     - docker:19.03.6-dind
#   script:
#     - echo "$CI_JOB_TOKEN" | docker login $CI_REGISTRY --username=gitlab-ci-token --password-stdin
#     - export BASE_IMAGE=$(grep -oE 'FROM .+$' Dockerfile | head -n 1 | cut -d ' ' -f 2)
#     - docker pull $CI_REGISTRY_IMAGE:latest || true
#     - docker pull $BASE_IMAGE
#     - docker build --cache-from $CI_REGISTRY_IMAGE:latest,$BASE_IMAGE --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') -t $IMAGE_TAG -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA -f Dockerfile .
#     - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
#     - docker push $IMAGE_TAG

# include:
#   - template: Container-Scanning.gitlab-ci.yml

# release image:
#   stage: release
#   image: docker:19.03.6
#   services:
#     - docker:19.03.6-dind
#   script:
#     - . build_info
#     - echo "$CI_JOB_TOKEN" | docker login $CI_REGISTRY --username=gitlab-ci-token --password-stdin
#     - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA || true
#     - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE:latest
#     - docker push $CI_REGISTRY_IMAGE:latest
#     - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE:v$RELEASE_VERSION
#     - docker push $CI_REGISTRY_IMAGE:v$RELEASE_VERSION
#   only:
#     - master

# release dockerhub:
#   stage: release
#   image: docker:19.03.6
#   services:
#     - docker:19.03.6-dind
#   variables:
#     REGISTRY_USER: ${DOCKER_HUB_USER}
#     REGISTRY_PASSWORD: ${DOCKER_HUB_PASSWORD}
#     REGISTRY: docker.io
#     REGISTRY_IMAGE: index.docker.io/derfabianpeter/${CI_PROJECT_NAME}
#   script:
#     - . build_info
#     - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY --username=${CI_REGISTRY_USER} --password-stdin
#     - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA || true
#     # Log in to Docker Hub
#     - echo "$REGISTRY_PASSWORD" | docker login $REGISTRY --username=${REGISTRY_USER} --password-stdin
#     - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA $REGISTRY_IMAGE:latest
#     - docker push $REGISTRY_IMAGE:latest
#     - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA $REGISTRY_IMAGE:v$RELEASE_VERSION
#     - docker push $REGISTRY_IMAGE:v$RELEASE_VERSION
#   only:
#     - master

release version:
  stage: release
  image: registry.gitlab.com/juhani/go-semrel-gitlab:v0.21.1
  script:
    - rm -f release_info
    - mv build_info release_info
    - . release_info
    - release changelog
    - release commit-and-tag CHANGELOG.md release_info
  only:
    - master
  tags:
    - build